import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import localFont from "next/font/local";

import { Header } from "@/layout/Header";
import { Footer } from "@/layout/Footer";

import "./globals.css";

const unbounded = Unbounded({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-unbounded",
});

const fixelDisplay = localFont({
  src: [
    {
      path: "../../public/fonts/FixelDisplay-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/FixelDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/FixelDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/FixelDisplay-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-fixelDisplay",
});

export const metadata: Metadata = {
  title: "De-tort",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body className={`${fixelDisplay.variable} ${unbounded.className}`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
